spring:
  application:
    name: postgres

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2604
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true